// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbpahpcaoeymljmupykm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicGFocGNhb2V5bWxqbXVweWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mzg4NzcsImV4cCI6MjA2NzMxNDg3N30.IBM4WBypR6oay2oImGL2TnX0r9cIEG_JAjn2hCJI0A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});